site_name: WV Arduino Club Tutorials

# github repository icon setup
repo_url: https://github.com/WVarduinoclub/tutorials
repo_name: Arduino Club Tutorials

# edit button specs (right now, the edit is enabled)
# edit_uri: ""

copyright: Copyright &copy; 2021 WV Arduino Club

# Code Highlighting
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences


# Site navigation
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - 'Python': 
    - 'Setting up python' : 'python-tutorials/Setup.md'
    - 'The Basics' : 'python-tutorials/lesson1.md'
    - 'Lists, Sets, Dictionaries, and Tuples' : 'python-tutorials/lesson2.md'
    - 'A quick recap' : 'python-tutorials/lesson3.md'
    - 'If Statements and Operators' : 'python-tutorials/lesson4.md'
    - 'For and While loops' : 'python-tutorials/lesson5.md'
    - 'Custom functions' : 'python-tutorials/lesson6.md'
    - 'Libraries and Modules' : 'python-tutorials/lesson7.md'
    - 'Putting it All Together' : 'python-tutorials/lesson8.md'

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections