site_name: WV Arduino Club Tutorials

# github repository icon setup
repo_url: https://github.com/WVarduinoclub/tutorials
repo_name: Arduino Club Tutorials

# edit button specs (right now, the edit is enabled)
# edit_uri: ""

site_url: https://wvarduinoclub.github.io/tutorials/

copyright: Copyright &copy; 2021 WV Arduino Club

# Code Highlighting
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences


# Site navigation
nav:
  - Home: 'index.md'
  - 'Python': 
    - 'Setting up python' : 'python-tutorials/Setup.md'
    - 'The Basics' : 'python-tutorials/lesson1.md'
    - 'Lists, Sets, Dictionaries, and Tuples' : 'python-tutorials/lesson2.md'
    - 'A quick recap' : 'python-tutorials/lesson3.md'
    - 'If Statements and Operators' : 'python-tutorials/lesson4.md'
    - 'For and While loops' : 'python-tutorials/lesson5.md'
    - 'Custom functions' : 'python-tutorials/lesson6.md'
    - 'Libraries and Modules' : 'python-tutorials/lesson7.md'
    - 'Putting it All Together' : 'python-tutorials/lesson8.md'
  - 'Arduino':
    - 'Arduino Presentation' : 'arduino-tutorials/arduino-presentation.md'

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
extra:
  analytics:
    provider: google
    property: G-B1ZNY7M2D1
    # consent:
    #   title: Cookie consent
    #   description:
    #     We use cookies to recognize your repeated visits and preferences, as well
    #     as to measure the effectiveness of our documentation and whether users
    #     find what they're searching for. With your consent, you're helping us to
    #     make our documentation better.
